//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Producto { get; set; }
        public double Precioxunidad { get; set; }
        public int Cantidad { get; set; }
        public string Cliente { get; set; }
        public string CodigoCliente { get; set; }
        public double DescuentoCliente { get; set; }
        public double Total { get; set; }
        public double PrecioTotal { get; set; }
        public int Factura { get; set; }
    }
}
