//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCliFactu
    {
        public string ApellidoCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Codigo { get; set; }
        public string Producto { get; set; }
        public double Precioxunidad { get; set; }
        public string CodCli { get; set; }
        public double Total { get; set; }
        public double PrecioTotal { get; set; }
    }
}
